-- QUANTIDADE DE CONQUISTAS PLATINA POR CONTA QUE TENHAM MAIS QUE A MEDIA (GROUP BY HAVING)--
SELECT G.USERNAME_LOGADO, COUNT(*) AS QTD
FROM GANHAR G
WHERE (G.NOME_APP, G.NOME_CONQUISTA) IN (SELECT C.NOME_APP, C.NOME_CONQUISTA FROM CONQUISTA C WHERE C.RARIDADE = 'PLATINA')
GROUP BY G.USERNAME_LOGADO
HAVING QTD > AVG(QTD);

-- USERNAMES E JOGOS JOGADOS A PARTIR DE 05/09/2023 EM RECIFE (INNER JOIN) --
SELECT USERNAME_LOGADO, NOME_APP
FROM CONTA INNER JOIN HISTORICO_EXEC ON (USERNAME = USERNAME_LOGADO)
WHERE FIM > TO_DATE('05/09/2023', 'DD/MM/YYYY HH24:MI:SS') AND CIDADE = 'RECIFE';
