-- QUANTIDADE DE CONQUISTAS PLATINA POR CONTA QUE TENHAM MAIS QUE A MEDIA (GROUP BY HAVING)--
SELECT G.USERNAME_LOGADO, COUNT(*) AS QTD
FROM GANHAR G
WHERE (G.NOME_APP, G.NOME_CONQUISTA) IN (SELECT C.NOME_APP, C.NOME_CONQUISTA FROM CONQUISTA C WHERE C.RARIDADE = 'PLATINA')
GROUP BY G.USERNAME_LOGADO
HAVING QTD > AVG(QTD);

-- USERNAMES E JOGOS JOGADOS A PARTIR DE 05/09/2023 EM RECIFE (INNER JOIN) --
SELECT USERNAME_LOGADO, NOME_APP
FROM CONTA INNER JOIN HISTORICO_EXEC ON (USERNAME = USERNAME_LOGADO)
WHERE FIM > TO_DATE('05/09/2023', 'DD/MM/YYYY HH24:MI:SS') AND CIDADE = 'RECIFE';

-- USERNAMES E JOGOS COMPRADOS (NULL SE NÃO HOUVER JOGOS) (OUTER JOIN)--
SELECT CO.USERNAME AS USERNAME, A.NOME AS JOGO
FROM CONTA CON LEFT OUTER JOIN COMPRAR C ON (CON.USERNAME = C.USERNAME) INNER JOIN APLICATIVO A ON (C.CÓDIGO = A.CÓDIGO)
WHERE A.CÓDIGO = (SELECT CÓDIGO
                FROM JOGO
                WHERE A.CÓDIGO = J.CÓDIGO)
ORDER BY CO.USERNAME ASC, A.NOME ASC
