-----------------------
--CRIACAO DAS TABELAS--
-----------------------

-- CRIA TABELA CONTA
    CREATE TABLE CONTA(
    USERNAME VARCHAR2(15),
    SALDO NUMBER(7, 2),
    LOC_PAIS VARCHAR2(20),
    LOC_ESTADO VARCHAR2(20),
    LOC_CIDADE VARCHAR2(20),
    EM_USO NUMBER(1),
    USERNAME_REDE VARCHAR2(15),
    CONSTRAINT PK_CONTA PRIMARY KEY (USERNAME),
    CONSTRAINT FK_CONTA_REDE UNIQUE (USERNAME_REDE),
    CONSTRAINT BOOLEAN CHECK (EM_USO IN (0, 1))
);

-- CRIA TABELA AMIGO
CREATE TABLE AMIGO(
    USERNAME1 VARCHAR2(15),
    USERNAME2 VARCHAR2(15),
    DATA_AMIZADE DATE,
    CONSTRAINT PK_AMIGO PRIMARY KEY (USERNAME1, USERNAME2),
    CONSTRAINT FK_CONTA_AMIGO1 FOREIGN KEY (USERNAME1) REFERENCES CONTA,
    CONSTRAINT FK_CONTA_AMIGO2 FOREIGN KEY (USERNAME2) REFERENCES CONTA
);

-- CRIA TABELA USUARIO
CREATE TABLE USUARIO(
    CODIGO VARCHAR2(5),
    CONSTRAINT PK_USUARIO PRIMARY KEY (CODIGO)
);

-- CRIA TABELA TEM_ACESSO
CREATE TABLE TEM_ACESSO(
    USERNAME VARCHAR2(15),
    CODIGO VARCHAR2(5),
    CONSTRAINT PK_ACESSO PRIMARY KEY (USERNAME, CODIGO),
    CONSTRAINT FK_USUARIO_ACESSO FOREIGN KEY (CODIGO) REFERENCES USUARIO,
    CONSTRAINT FK_CONTA_ACESSO FOREIGN KEY (USERNAME) REFERENCES CONTA
);

-- CRIA TABELA EMPRESA
CREATE TABLE EMPRESA(
    CNPJ VARCHAR2(14),
    NOME VARCHAR2(20),
    CONSTRAINT PK_EMPRESA PRIMARY KEY (CNPJ)
);


-- CRIA TABELA APLICATIVO
CREATE TABLE APLICATIVO(
    NOME VARCHAR2(20),
    PRECO_ATUAL NUMBER(5,2),
    DATA_LANCAMENTO DATE,
    CNPJ_DESENVOLVEDOR VARCHAR2(14),
    CNPJ_DISTRIBUIDOR VARCHAR2(14),
	TIPO VARCHAR2(10),
    CONSTRAINT PK_APLICATIVO PRIMARY KEY (NOME),
    CONSTRAINT FK_APLICATIVO_DESENVOLVEDOR FOREIGN KEY (CNPJ_DESENVOLVEDOR) REFERENCES EMPRESA,
    CONSTRAINT FK_APLICATIVO_DISTRIBUIDOR FOREIGN KEY (CNPJ_DISTRIBUIDOR) REFERENCES EMPRESA,
	CONSTRAINT TIPO_HERANCA CHECK (TIPO IN ('JOGO', 'SOFTWARE'))
);

-- CRIA TABELA CATEGORIA
CREATE TABLE CATEGORIA(
    NOME VARCHAR2(5),
    CATEG VARCHAR2(20),
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (NOME, CATEG),
    CONSTRAINT FK_APLICATIVO_CATEGORIA FOREIGN KEY (NOME) REFERENCES APLICATIVO
);

-- CRIA TABELA EXPANSAO
CREATE TABLE EXPANSAO(
    NOME_JOGO VARCHAR2(5),
	NOME_EXPANSAO VARCHAR2(5),
    CONSTRAINT PK_EXPANSAO PRIMARY KEY (NOME_JOGO),
    CONSTRAINT FK_EXPANSAO_JOGO FOREIGN KEY (NOME_JOGO) REFERENCES APLICATIVO
);

-- CRIA TABELA COMPRA
CREATE TABLE COMPRA(
    USERNAME VARCHAR2(15),
    NOME VARCHAR2(5),
    PRECO_COMPRA NUMBER(5,2),
    DATA_COMPRA DATE,
    CONSTRAINT PK_COMPRA PRIMARY KEY (USERNAME, NOME),
    CONSTRAINT FK_COMPRA_CONTA FOREIGN KEY (USERNAME) REFERENCES CONTA,
    CONSTRAINT FK_COMPRA_APLICATIVO FOREIGN KEY (NOME) REFERENCES APLICATIVO
);

-- CRIA TABELA HISTORICO_EXEC
CREATE TABLE HISTORICO_EXEC(
    CODIGO_USUARIO VARCHAR2(5),
    USERNAME_LOGADO VARCHAR2(15),
    NOME_APP VARCHAR2(5),
    INICIO DATE,
    FIM DATE,
    CONSTRAINT PK_HISTORICO PRIMARY KEY (CODIGO_USUARIO, USERNAME_LOGADO, NOME_APP, INICIO),
    CONSTRAINT FK_HISTORICO_USUARIO FOREIGN KEY (CODIGO_USUARIO) REFERENCES USUARIO,
    CONSTRAINT FK_HISTORICO_LOGADO FOREIGN KEY (USERNAME_LOGADO) REFERENCES CONTA,
    CONSTRAINT FK_HISTORICO_APLICATIVO FOREIGN KEY (NOME_APP) REFERENCES APLICATIVO
);

-- CRIA TABELA CONQUISTA
CREATE TABLE CONQUISTA(
    NOME_CONQUISTA VARCHAR2(20),
    DESCRICAO VARCHAR2(100),
    RARIDADE VARCHAR2(15),
    CODIGO_USUARIO VARCHAR2(5),
    USERNAME_LOGADO VARCHAR2(15),
    NOME_APP VARCHAR2(5),
    INICIO DATE,
    CONSTRAINT PK_CONQUISTA PRIMARY KEY (NOME_CONQUISTA),
    CONSTRAINT FK_CONQUISTA_HISTORICO FOREIGN KEY (CODIGO_USUARIO, USERNAME_LOGADO, NOME_APP, INICIO) REFERENCES HISTORICO_EXEC
);
