-- COMPRAR_APP --

CREATE OR REPLACE PROCEDURE COMPRAR_APP (COD_APP VARCHAR2, USERNAME VARCHAR2) IS
PRECO_APP NUMBER;
SALDO NUMBER;
DATA DATE;

BEGIN
    SELECT CURRENT_DATE INTO DATA FROM DUAL;
    SELECT PRECO_ATUAL INTO PRECO_APP FROM APLICATIVO A WHERE A.CODIGO = COD_APP;
    SELECT C.SALDO INTO SALDO FROM CONTA C WHERE C.USERNAME = USERNAME;

    IF SALDO >= PRECO_APP THEN
        INSERT INTO COMPRA VALUES (USERNAME, COD_APP, PRECO_APP, DATA); --ADICIONA NA BIBLIOTECA
        UPDATE CONTA C SET SALDO = (SALDO - PRECO_APP) WHERE C.USERNAME = USERNAME; --ATUALIZA O SALDO
        DBMS_OUTPUT.PUT_LINE('APLICATIVO COMPRADO! ABRE LOGO AÍ!');
    ELSE
        DBMS_OUTPUT.PUT_LINE('SALDO INSUFICIENTE! FAZ O PIX!');
    END IF;
END;
