-- COMPRAR APLICATIVO --

CREATE OR REPLACE PROCEDURE COMPRAR_APP (NOME_APP VARCHAR2, USERNAME VARCHAR2) IS
PRECO_APP NUMBER;
SALDO NUMBER;
DATA DATE;

BEGIN
	SELECT CURRENT_DATE INTO DATA FROM DUAL;
	SELECT PRECO_ATUAL INTO PRECO_APP FROM APLICATIVO A WHERE A.NOME = NOME_APP;
	SELECT C.SALDO INTO SALDO FROM CONTA C WHERE C.USERNAME = USERNAME;

	IF SALDO >= PRECO_APP THEN
		INSERT INTO COMPRA VALUES (USERNAME, NOME_APP, PRECO_APP, DATA); --ADICIONA NA BIBLIOTECA
		UPDATE CONTA C SET SALDO = (SALDO - PRECO_APP) WHERE C.USERNAME = USERNAME; --ATUALIZA O SALDO
		DBMS_OUTPUT.PUT_LINE('APLICATIVO COMPRADO! ABRE LOGO AÍ!');
	ELSE
		DBMS_OUTPUT.PUT_LINE('SALDO INSUFICIENTE! FAZ O PIX!');
	END IF;
END;

-- PUBLICA APLICATIVO --

CREATE OR REPLACE TYPE myarray IS VARRAY(10) OF VARCHAR2(20);

CREATE OR REPLACE PROCEDURE publicar_app (NOME VARCHAR2, EMP_DES VARCHAR2, EMP_DIS VARCHAR2, CATEGORIAS myarray, PRECO NUMBER, TIPO VARCHAR2) IS
DATA DATE;
CNT_DES NUMBER;
CNT_DIS NUMBER;

BEGIN
	SELECT COUNT(*) INTO CNT_DES FROM EMPRESA WHERE CNPJ = EMP_DES;
	SELECT COUNT(*) INTO CNT_DIS FROM EMPRESA WHERE CNPJ = EMP_DIS;

	IF CNT_DES > 0 AND CNT_DIS > 0 THEN
		SELECT CURRENT_DATE INTO DATA FROM DUAL;
		INSERT INTO APLICATIVO VALUES (NOME, PRECO, DATA, EMP_DES, EMP_DIS, TIPO);

		FOR I IN 1 .. CATEGORIAS.COUNT LOOP
			INSERT INTO CATEGORIA VALUES (NOME, CATEGORIAS(I));
		END LOOP;
	ELSE
		DBMS_OUTPUT.PUT_LINE('CNPJ ERRADO, CARAI! AJEITA ISSO AI!');
	END IF;

END;

-- EXECUTAR APLICATIVO--

CREATE OR REPLACE PROCEDURE EXECUTAR_APP (COD_USER VARCHAR, USERNAME_LOG VARCHAR, NOME_APP VARCHAR) IS 
    DATA_INICIO DATE;
	CNT NUMBER;
	USO NUMBER(1);
BEGIN
	SELECT EM_USO INTO USO FROM CONTA WHERE USERNAME = USERNAME_LOG;

	IF USO = 0 THEN
        SELECT COUNT(*) INTO CNT FROM (SELECT NOME FROM COMPRA WHERE NOME = NOME_APP AND USERNAME IN 
    								  (SELECT USERNAME FROM CONTA WHERE USERNAME IN
    								  (SELECT USERNAME FROM TEM_ACESSO WHERE CODIGO = COD_USER)));
    	IF (CNT > 0) THEN
        	SELECT CURRENT_DATE INTO DATA_INICIO FROM DUAL;
    		INSERT INTO HISTORICO_EXEC VALUES(COD_USER, USERNAME_LOG, NOME_APP, DATA_INICIO, NULL);
    		UPDATE CONTA SET EM_USO = 1 WHERE USERNAME = USERNAME_LOG;
        	DBMS_OUTPUT.PUT_LINE('Aplicativo está executando.');
    	ELSE
        	DBMS_OUTPUT.PUT_LINE('Você não tem acesso à esse aplicativo.');
    	END IF;
	ELSE
            DBMS_OUTPUT.PUT_LINE('Conta ' || USERNAME_LOG || ' já está em uso.');
	END IF;
END;

-- CADASTRAR EMPRESA -- 

CREATE OR REPLACE PROCEDURE CADASTRAR_EMPRESA (CNPJ VARCHAR2, NOME VARCHAR2) IS

BEGIN
    INSERT INTO EMPRESA VALUES (CNPJ, NOME);
	DBMS_OUTPUT.PUT_LINE('EMPRESA CADASTRADA COM SUCESSO!');
END;

